background {
path = ~/Wallpaper/wallpaper.jpg

```
blur_passes = 3
blur_size = 8

noise = 0.0117
contrast = 1.1
brightness = 0.9
vibrancy = 0.2
```

}

general {
hide_cursor = false
}

# ======================

# CLOCK

# ======================

label {
monitor =

```
text = cmd[update:1000] echo "$(date +"%H:%M")"

color = rgba(f5f1faff)

font_size = 96
font_family = JetBrainsMono Nerd Font

position = 0, 180

halign = center
valign = center
```

}

# ======================

# DATE

# ======================

label {
monitor =

```
text = cmd[update:60000] echo "$(date +"%A, %d %B %Y")"

color = rgba(b7a1e6ff)

font_size = 22
font_family = JetBrainsMono Nerd Font

position = 0, 95

halign = center
valign = center
```

}

# ======================

# NOW PLAYING HEADER

# ======================

label {
monitor =

```
text = ♫ NOW PLAYING

color = rgba(d8b46aff)

font_size = 12
font_family = JetBrainsMono Nerd Font

position = 0, 15

halign = center
valign = center
```

}

# ======================

# SONG TITLE

# ======================

label {
monitor =

```
text = cmd[update:1000] playerctl metadata title

color = rgba(9d7cd8ff)

font_size = 20
font_family = JetBrainsMono Nerd Font

position = 0, -15

halign = center
valign = center
```

}

# ======================

# ARTIST

# ======================

label {
monitor =

```
text = cmd[update:1000] playerctl metadata artist

color = rgba(b7a1e6cc)

font_size = 15
font_family = JetBrainsMono Nerd Font

position = 0, -45

halign = center
valign = center
```

}

# ======================

# PLAYER STATUS

# ======================

label {
monitor =

```
text = cmd[update:1000] playerctl status

color = rgba(d8b46aaa)

font_size = 12
font_family = JetBrainsMono Nerd Font

position = 0, -70

halign = center
valign = center
```

}

# ======================

# PASSWORD FIELD

# ======================

input-field {
monitor =

```
size = 340, 60

outline_thickness = 3

dots_size = 0.25
dots_spacing = 0.20

outer_color = rgba(9d7cd8ff)
inner_color = rgba(141421ee)

font_color = rgba(f5f1faff)

fade_on_empty = false

placeholder_text = Enter Password...

position = 0, -140

halign = center
valign = center

rounding = 18
```

}

# ======================

# USERNAME

# ======================

label {
monitor =

```
text = cmd[update:60000] echo "$USER"

color = rgba(d8b46aff)

font_size = 20
font_family = JetBrainsMono Nerd Font

position = 0, -220

halign = center
valign = center
```

}

# ======================

# HINT

# ======================

label {
monitor =

```
text = Press ENTER to Unlock

color = rgba(ffffff99)

font_size = 12
font_family = JetBrainsMono Nerd Font

position = 0, -280

halign = center
valign = center
```

}
