-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
        },
    },
})

-- Animations
hl.animation({
    leaf = "workspaces",
    enabled = false,
})
